php_version: "8.4"
apache_packages:
  - apache2
  - libapache2-mod-php
php_packages:
  - php{{ php_version }}
  - php{{ php_version }}-ctype
  - php{{ php_version }}-curl
  - php{{ php_version }}-dom
  - php{{ php_version }}-gd
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-posix
  - php{{ php_version }}-session
  - php{{ php_version }}-simplexml
  - php{{ php_version }}-xmlreader
  - php{{ php_version }}-xmlwriter
  - php{{ php_version }}-zip
  - php{{ php_version }}-zlib
  - php{{ php_version }}-libxml
  - php{{ php_version }}-sqlite3