webroot_domain: kgregory.net

nextcloud_servername: nextcloud.kgregory.net
nextcloud_serveraliases: []

letsencrypt_primary_domain: kgregory.net
letsencrypt_domains:
  - kgregory.net
  - nextcloud.kgregory.net
  - git.kgregory.net
  - blog.kgregory.net

ssl_cert_path: "/etc/letsencrypt/live/{{ letsencrypt_primary_domain }}/fullchain.pem"
ssl_key_path:  "/etc/letsencrypt/live/{{ letsencrypt_primary_domain }}/privkey.pem"  