nextcloud_serveraliases: []
nextcloud_servername: nextcloud.kgregory.net

letsencrypt_primary_domain: kgregory.net
letsencrypt_domains:
  - kgregory.net
  - nextcloud.kgregory.net
  - git.kgregory.net
  - blog.kgregory.net