- name: Create data directory outside web root
  file:
    path: "{{ nextcloud_data_dir }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0750' # Very restrictive permissions

- name: Run Nextcloud Web-Installer via CLI
  become: yes
  become_user: www-data  # Must run as the webserver user
  command:
    argv:
      - php
      - occ
      - maintenance:install
      - --database
      - sqlite
      - --admin-user
      - "gregory"
      - --admin-pass
      - "{{ vault_nextcloud_admin_password }}"
      - --data-dir
      -  "{{ nextcloud_data_dir }}"
    chdir: /var/www/nextcloud
    creates: /var/www/nextcloud/config/config.php
  register: nextcloud_install_result  

- name: Configure Nextcloud trusted_domains
  become: yes
  become_user: www-data
  command:
    # We use index + 1 because localhost is index 0
    cmd: "php occ config:system:set trusted_domains {{ item_index + 1 }} --value={{ item }}"
    chdir: /var/www/nextcloud
  loop: "{{ [nextcloud_servername] + (nextcloud_serveraliases | default([])) }}"
  loop_control:
    index_var: item_index
  when: nextcloud_install_result.changed

- name: Set Nextcloud Pretty URL parameters  
  ansible.builtin.shell:
    cmd: "php occ config:system:set 'htaccess.RewriteBase' --value='/'"
    chdir: /var/www/nextcloud
  become: yes
  become_user: www-data
  when: nextcloud_install_result.changed

- name: Update Nextcloud .htaccess
  ansible.builtin.command:
    cmd: php /var/www/nextcloud/occ maintenance:update:htaccess
  become: yes
  become_user: www-data
  when: nextcloud_install_result.changed  