- name: Ensure environment is ready
  include_tasks: roles/apache2/tasks/check_snippet.yml
  vars:
    vhost_name: "WebRoot(/)"

- name: "Configure WebRoot(/) Apache site"
  include_tasks: roles/apache2/tasks/configure_site.yml
  vars:
    site_src: webroot.conf.j2
    site_name: webroot.conf

- name: Disable default Apache site
  command: a2dissite 000-default.conf
  args:
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: Reload Apache gracefully