$ANSIBLE_VAULT;1.1;AES256
30376535316431316538653362363535643235623538613665373161666435646239343032643864
6663393930643762333862393163303635336239356536390a663938373637373332393234306437
30643863386134633531643830333536623435643335396531643337343535663138313933333837
3734393466313832630a616461386537383931646165313463343834343038383235376666303433
63616664616435303563313861316163376565393765616435373033623932316562643239666462
30633463653566313330363432363834623830326535303064396132633231663438623361333161
35356466323334353936393661393463373531666530376432366530646263333938393231323066
30626539346361333864616439393339663730373566386263316431363161363233356233386135
31626638656531636530613261313934383766353638623634386638303337313564
