webroot_domain:       kgregory.test
nextcloud_servername: nextcloud.kgregory.test

nextcloud_serveraliases:
  - 192.168.122.115

ssl_cert_path: "/etc/ssl/ansible/fullchain.pem"
ssl_key_path:  "/etc/ssl/ansible/privkey.pem"