- name: Install nginx
  apt:
    name:
      - nginx
    state: present

- name: Copy Nextcloud site configuration
  copy:
    src: nextcloud-nginx.conf
    dest: /etc/nginx/sites-available/nextcloud
    owner: root
    group: root
    mode: '0644'
  notify: Reload Nginx

- name: Enable Nextcloud site
  file:
    src: /etc/nginx/sites-available/nextcloud
    dest: /etc/nginx/sites-enabled/nextcloud
    state: link
  notify: Reload Nginx

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Reload Nginx