- name: Configure IP Forwarding
  hosts: wireguard_hosts
  become: yes
  tasks:
    - name: Enable IPv4 forwarding in sysctl
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes